### ISSUE TITLE
Update mion-testing documentation

### ISSUE THREAD

**Issue by kprosise** [NetworkGradeLinux/mion-testing#1] opened 2020-11-04 18:12 UTC
The information on package tests and runtime tests needs to be update, with information specific to mion will be added in the near future.

**Comment by johntoomey** [comment] 2021-01-15 12:28
this is a duplicate of the test plan issue - @kprosise to check that that is tracked somewhere else and close this out

**Comment by johntoomey** [comment] 2021-01-15 12:32
this is the original task i think: https://github.com/NetworkGradeLinux/meta-mion/issues/8

**Comment by johntoomey** [comment] 2021-01-15 14:37
i think this is covered by the test plan issue https://github.com/NetworkGradeLinux/mion-docs/issues/168

**Closed as completed by johntoomey** 2021-01-15 14:37 UTC
Labels: documentation
